name: Build Project
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - uses: actions/setup-node@v3
      with:
        node-version: '18.14'
        cache: 'yarn'
    - name: Deploy to github pages
      id: Deploy-to-github-pages
      uses: NextGenOP/ReactPagesAction@1.0.1
      with:
        username: 'NextGenOP'
        reponame: 'todolist-frontend'
        useyarn: 'true'
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        REACT_APP_NODE_ENV: ${{ secrets.REACT_APP_NODE_ENV }}
        REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        branch: gh-pages
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ID }}
        projectName: todolist-frontend
        directory: ./build
        # Optional: Enable this if you want to have GitHub Deployments triggered
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
